<?php
//Incluye los bloques o controladores y las paginas dependientes de cada uno
$blocks=array(
    'Page'=>[
        'index',
        'login',
        'menu',
        'exit'
    ],
    "Reporte"=>[
        "show",
        "getreportes",
        "store",
        "delete",
        "loadreportedetail",
        "postsolution",
        "update",
        "getcont"
    ],
    "Mantenimiento"=>[
        "show",
        "getall",
        "save",
        "savemante",
        "update",
        "gethistorial",
        "getcont"
    ],
    "Equipo"=>[
        "getall",
        "save",
        "show",
        "getmarca",
        "store",
        "getallunsigned",
        "update",
        "delete",
        "getbyuser"
    ],
    "Backup"=>[
        "show",
        "getall",
        "save",
        "getrespaldo",
        "update",
        "getcont"
    ],
    "Usuario"=>[
        "show",
        "getall",
        "asignar"
    ],
    "Inventario" => [
        "show",
        "getall",
        "store",
        "destroy",
        "update",
        "watch",
        "getinventario",
        "additeminventario",
        "edititeminventario",
        "destroyitem"
    ],
    "Archivo"=>[
        "save",
        "update",
        "show",
        "getall",
        "delete",
    ]
);
//Se pueden registrar varios bloques y varias paginas
?>